name: MetaOCaml
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  install:
    name: Install
    runs-on: ${{ matrix.os }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler: ["ocaml-variants.5.3.0+BER"]
        os: [ubuntu-latest]
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
            metaocaml: https://github.com/metaocaml/metaocaml-opam.git
            beta: https://github.com/ocaml/ocaml-beta-repository.git

      - name: Deps
        run: |
          opam install --yes ocamlfind ocamlbuild

      - name: Build
        run: |
          opam exec -- make

      - name: Test
        run: |
          opam exec -- make test
